services:
  # Main Playwright testing service
  playwright-tests:
    build:
      context: .
      dockerfile: Dockerfile
      target: testing
    volumes:
      - .:/app
      - /app/node_modules
      - ./test-results:/app/test-results
      - ./playwright-report:/app/playwright-report
    environment:
      - CI=true
      - NODE_ENV=test
      - PLAYWRIGHT_BROWSERS_PATH=/ms-playwright
    ports:
      - "3000:3000"
    command: >
      sh -c "
        echo 'Starting development server...' &&
        npm run dev &
        echo 'Waiting for server to start...' &&
        sleep 15 &&
        echo 'Running cross-device tests...' &&
        npm run test:cross-device
      "
    networks:
      - playwright-network
    shm_size: 2gb

  # Mobile-specific testing
  playwright-mobile:
    extends: playwright-tests
    command: >
      sh -c "
        npm run dev &
        sleep 15 &&
        npm run test:mobile
      "

  # Desktop-specific testing
  playwright-desktop:
    extends: playwright-tests
    command: >
      sh -c "
        npm run dev &
        sleep 15 &&
        npm run test:desktop
      "

  # Accessibility testing
  playwright-accessibility:
    extends: playwright-tests
    command: >
      sh -c "
        npm run dev &
        sleep 15 &&
        npm run test -- --grep @accessibility
      "

  # Performance testing
  playwright-performance:
    extends: playwright-tests
    command: >
      sh -c "
        npm run dev &
        sleep 15 &&
        npm run test -- --grep @performance
      "

  # Visual regression testing
  playwright-visual:
    extends: playwright-tests
    command: >
      sh -c "
        npm run dev &
        sleep 15 &&
        npm run test -- --update-snapshots
      "

  # Test report server
  test-report:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./playwright-report:/usr/share/nginx/html
    networks:
      - playwright-network
    profiles:
      - report

networks:
  playwright-network:
    driver: bridge
