services:
  # Main application service
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - NEXT_TELEMETRY_DISABLED=1
    networks:
      - casino-network
    restart: unless-stopped

  # Production build service
  app-prod:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    networks:
      - casino-network
    profiles:
      - production

  # Database service (for future use)
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: casino_db
      POSTGRES_USER: casino_user
      POSTGRES_PASSWORD: casino_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - casino-network
    profiles:
      - database

  # Redis service (for caching and sessions)
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - casino-network
    profiles:
      - cache

  # Nginx reverse proxy
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - app
    networks:
      - casino-network
    profiles:
      - proxy

volumes:
  postgres_data:
  redis_data:

networks:
  casino-network:
    driver: bridge
